# Copyright 2017 the authors. See the 'Copyright and license' section of the
# README.md file at the top-level directory of this repository.
#
# Licensed under the Apache License, Version 2.0 (the LICENSE file). This file
# may not be copied, modified, or distributed except according to those terms.

language: rust
rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx
# Load travis-cargo
before_script:
  - pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - set -x; set -e; for script in */travis.sh; do
        dir=$(dirname "$script");
        file=$(basename "$script");
        pushd "$dir";
        ./$file;
        popd;
    done
  - ./test-scripts/check-copyright-comments.sh

env:
  global:
    # Override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
