# Copyright 2017 the authors. See the 'Copyright and license' section of the
# README.md file at the top-level directory of this repository.
#
# Licensed under the Apache License, Version 2.0 (the LICENSE file). This file
# may not be copied, modified, or distributed except according to those terms.

language: rust
rust:
  - nightly
os:
  - linux
  - osx
script:
  - set -x; set -e; for script in */travis.sh; do
        dir=$(dirname "$script");
        file=$(basename "$script");
        pushd "$dir";
        ./$file;
        popd;
    done
